version: "3"

services:
  app:
    build: .
    ports:
      - 50051:50051
    volumes:
      - .:/home/node/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - NODE_ENV=production

  db:
    image: postgres:13-alpine
    restart: always
    logging:
      driver: none
    tty: true
    volumes:
      - .pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=codepix
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    logging:
      driver: none
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - "9000:80"
    depends_on:
      - db
